services:
  postgres:
    image: postgres:15-alpine
    container_name: plagiarism_postgres1
    restart: always
    environment:
      POSTGRES_DB: plagiarism
      POSTGRES_USER: plagiarism
      POSTGRES_PASSWORD: plagiarism
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    networks:
      - plagiarism
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: plagiarism_rabbitmq1
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Management UI
    networks:
      - plagiarism
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
  rabbitmq_data:

networks:
  plagiarism:
    external: true
    name: plagiarism
